### PR TITLE
update pg driver to current 42.3.1

### PR DESCRIPTION
**Pull request by amandel**
Update the encapsulated JDBC driver, besides several updates the version is needed to connect to a current hardened PostgreSQL database. 

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
@timja hi, @amandel reached out to me by email to get the pg-driver bumped. I merged the changes before discovering that you are the new maintainer of this library. Please feel free to rollback if you are uncomfortable with this change.

@amandel with which plugin are you using the pg-driver? is it with the Jenkins Maven Plugin that is probably the most adopted plugin that uses the pg-driver? I'm asking to understand how we can test before releasing.

**Comment by amandel** [comment]
@cyrille-leclerc - It is https://plugins.jenkins.io/pipeline-maven/

**Comment by timja** [comment]
No worries go for it

**Comment by timja** [comment]
@cyrille-leclerc seems like you're the only maintainer of this https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-postgresql-api.yml

I have the database postgres plugin which doesn't use the API plugin:
https://github.com/jenkinsci/database-postgresql-plugin/blob/master/pom.xml#L28

**Comment by cyrille-leclerc** [comment]
@amandel can you please test https://github.com/jenkinsci/postgresql-api-plugin/releases/tag/postgresql-api-42.3.1-rc1 with the Pipeline Maven plugin.
Once you report success, I'll cut a GA release.

**Comment by amandel** [comment]
Thanks!

@cyrille-leclerc  - it is running (to serve the the ppeline-maven plugin) fine and looks good to me:
```
PipelineMavenPluginPostgreSqlDao - PostgreSQL 10.19 (Debian 10.19-1.pgdg90+1)
	JDBC URL: jdbc:postgresql://mypgserver/postgres
	Table JENKINS_MASTER: 1 rows
	Table MAVEN_ARTIFACT: 615941 rows
	Table JENKINS_JOB: 6061 rows
	Table JENKINS_BUILD: 35222 rows
	Table MAVEN_DEPENDENCY: 888847 rows
	Table GENERATED_MAVEN_ARTIFACT: 480687 rows
	Table MAVEN_PARENT_PROJECT: 116825 rows
	Table JENKINS_BUILD_UPSTREAM_CAUSE: 2731 rows
 Performances: 
	 find: totalDurationInMs=32259, count=72
	 write: totalDurationInMs=238004, count=1030
```

**Comment by cyrille-leclerc** [comment]
Thanks! please see https://github.com/jenkinsci/postgresql-api-plugin/releases/tag/postgresql-api-42.3.1

**Pull request merged**
